*************************************************************************
*HEADING
*RESTART,READ,STEP=3,WRITE
*PARAMETER
PRESS =  2.5
OD =  645.82
LOAD_70 =  381
LOAD_100 =  431
LOAD_140 =  481
*************************************************************************
PLATE_HT = OD/2 + 7.0
UNIT_CONV = 1000
PRESSURE = PRESS * 9.81E-2 * (UNIT_CONV)**2
PLATE = PLATE_HT/UNIT_CONV
LOAD1 = LOAD_70*9.81
LOAD2 = LOAD_100*9.81
LOAD3 = LOAD_140*9.81
*************************************************************************
*STEP,INC=50,NLGEOM
4: -50 Vertical Stiffness
*STATIC
 0.25, 1.0
*CONTROLS,PARAMETERS=TIME INCREMENTATION
 8, 10, 9, 16, 10, 4, 12, 5, 6, 3
 0.50, 0.50, 0.50, 0.85, 0.50, 0.50, 1.50, 0.75
*CHANGE FRICTION, INTERACTION=GRATING
*FRICTION
 0.7
*BOUNDARY,OP=NEW
 NROAD,2,6,
 NRFLANGE,1,,
 NRFLANGE,2,,0.10
 NRFLANGE,3,6,
 NLFLANGE,1,,
 NLFLANGE,2,,-0.10
 NLFLANGE,3,6,
*CLOAD
 NROAD,1,-<LOAD1>
*NODE PRINT, NSET=NROAD, TOTALS=YES, FREQUENCY=1
 U
*NODE PRINT, NSET=NFLANGE, TOTALS=YES, FREQUENCY=1
 RF
*OUTPUT,FIELD,FREQUENCY=99
*ELEMENT OUTPUT
 S,E,SINV,ENER
*ELEMENT OUTPUT,REBAR
 S,RBFOR,RBANG
*NODE OUTPUT
 U,RF,CF,COORD,
*CONTACT OUTPUT
 CSTRESS,CDISP,
*NODE FILE,FREQ=20
 COORD,U,
*EL FILE,REBAR,FREQ=20
 S,RBFOR,
*RESTART,WRITE,FREQUENCY=99
*END STEP
*************************************************************************
*STEP,INC=50,NLGEOM
5: +50 Vertical Stiffness
*STATIC
 0.25, 1.0
*CONTROLS,PARAMETERS=TIME INCREMENTATION
 8, 10, 9, 16, 10, 4, 12, 5, 6, 3
 0.50, 0.50, 0.50, 0.85, 0.50, 0.50, 1.50, 0.75
*BOUNDARY,OP=NEW
 NROAD,2,6,
 NRFLANGE,1,,
 NRFLANGE,2,,0.10
 NRFLANGE,3,6,
 NLFLANGE,1,,
 NLFLANGE,2,,-0.10
 NLFLANGE,3,6,
*CLOAD
 NROAD,1,-<LOAD3>
*NODE PRINT, NSET=NROAD, TOTALS=YES, FREQUENCY=1
 U
*NODE PRINT, NSET=NFLANGE, TOTALS=YES, FREQUENCY=1
 RF
*OUTPUT,FIELD,FREQUENCY=99
*ELEMENT OUTPUT
 S,E,SINV,ENER
*ELEMENT OUTPUT,REBAR
 S,RBFOR,RBANG
*NODE OUTPUT
 U,RF,CF,COORD,
*CONTACT OUTPUT
 CSTRESS,CDISP,
*NODE FILE,FREQ=20
 COORD,U,
*EL FILE,REBAR,FREQ=20
 S,RBFOR,
*RESTART,WRITE,FREQUENCY=99
*END STEP
*************************************************************************
